### ISSUE TITLE
BranchCycle

### ISSUE THREAD

**Issue by munderseth** [s2testorg/testProjectBoard#8]
Branch Cycle Issue. 
 ```
  testspace:
    branch: test.branch
    specs: 
      path: cycle
 ```
